# Detect dangerous command execution
# Aligned with plugin Detection 3: Dangerous Commands
apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: openclaw-dangerous-commands
spec:
  kprobes:
    - call: "sys_execve"
      syscall: true
      args:
        - index: 0
          type: "string"
        - index: 1
          type: "string"
      selectors:
        # Monitor commands spawned by Node.js (OpenClaw)
        - matchBinaries:
            - operator: "In"
              values:
                - "/usr/bin/node"
                - "/usr/local/bin/node"
                - "/usr/bin/bash"
                - "/bin/bash"
                - "/usr/bin/sh"
                - "/bin/sh"
          matchArgs:
            - index: 0
              operator: "Postfix"
              values:
                # Data exfiltration tools
                - "/curl"
                - "/wget"
                - "/nc"
                - "/netcat"
                - "/ncat"
                - "/socat"
                
                # Destructive commands
                - "/rm"
                - "/dd"
                - "/mkfs"
                - "/shred"
                
                # Permission changes
                - "/chmod"
                - "/chown"
                
                # Crypto mining
                - "/xmrig"
                - "/minerd"
                - "/cpuminer"
                
                # Persistence tools
                - "/crontab"
                - "/at"
                
                # Privilege escalation
                - "/sudo"
                - "/su"
                - "/pkexec"
                
                # Container escape
                - "/nsenter"
                - "/unshare"
                
          matchActions:
            - action: Post

    # Catch shell invocations with inline commands
    - call: "sys_execve"
      syscall: true
      args:
        - index: 0
          type: "string"
        - index: 1
          type: "string"
      selectors:
        - matchBinaries:
            - operator: "In"
              values:
                - "/usr/bin/node"
                - "/usr/local/bin/node"
          matchArgs:
            # Catch: bash -c "dangerous command"
            - index: 0
              operator: "Postfix"
              values:
                - "/bash"
                - "/sh"
                - "/zsh"
            - index: 1
              operator: "Prefix"
              values:
                - "-c"
          matchActions:
            - action: Post
